"""
Django settings for Xtiane project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(+e!0gnq^_825*md(5ari9rwhsq6+_9=@8&=d49es$)d3dk86_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',        
    'usuarios', # MÓDULO GLOBAL DE ROLES Y CAPACIDADES (Nivel 1)
    # SUBMÓDULOS DE OPERACIÓN (Nivel 2)
    'notificaciones.areas',
    'notificaciones.notificadores',
    'notificaciones.bitacora',
]

MIDDLEWARE = [
    # ... middlewares por defecto de django ...    
     'django.middleware.security.SecurityMiddleware',
     'django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.common.CommonMiddleware',
     'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.auth.middleware.AuthenticationMiddleware',
     'django.contrib.messages.middleware.MessageMiddleware',
     'django.middleware.clickjacking.XFrameOptionsMiddleware',    
    # # Blindaje personalizado
    # 'usuarios.middleware.FiltroAreaMiddleware',
]

ROOT_URLCONF = 'Xtiane.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                 'django.template.context_processors.request',
                 'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Xtiane.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xtianedb',   # nombre de tu BD
        'USER': 'xtiane',          # tu usuario MySQL
        'PASSWORD': 'christian3mmanu3l',
        'HOST': '10.14.1.103',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # carpeta donde se recolectarán estáticos en producción
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # tus archivos estáticos manuales

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modelo de seguridad personalizado
AUTH_USER_MODEL = 'usuarios.UsuarioPerfil' 
#Modelo predeterminado de django
#AUTH_USER_MODEL = 'auth.User'

LOGIN_URL = '/login/'
# LOGIN_REDIRECT_URL = '/notificaciones/bitacora'
LOGIN_REDIRECT_URL = '/'  # Ahora apunta al dashboard
LOGOUT_REDIRECT_URL = '/login/'

# ADMIN_ENABLED = False 