# Generated by Django 5.2.14 on 2026-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='codigo_checador',
            field=models.IntegerField(blank=True, default=None, help_text='Código del empleado notificador', null=True, unique=True),
        ),
    ]
