# Generated by Django 5.2.14 on 2026-05-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('nombre_corto', models.CharField(db_column='NombreCorto', max_length=50)),
                ('extension_telefono', models.CharField(blank=True, db_column='ExtensionTelefono', max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cat_areas',
                'ordering': ['nombre'],
            },
        ),
    ]
