# Generated by Django 5.2.14 on 2026-05-19 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('notificadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio_memo', models.CharField(max_length=100)),
                ('situacion', models.CharField(blank=True, default='Asignada', max_length=50, null=True)),
                ('fecha_bitacora', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('destinatario', models.CharField(max_length=255)),
                ('expediente_asunto', models.TextField()),
                ('fecha_acuse', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('pdf_adjunto', models.FileField(blank=True, help_text='Solo archivos PDF', null=True, upload_to='pdfs/')),
                ('capturo', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to='areas.area')),
                ('notificador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bitacora', to='notificadores.notificador')),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['fecha_registro'],
            },
        ),
    ]
