# Generated by Django 5.2.14 on 2026-05-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['fecha_termino']},
        ),
        migrations.AddField(
            model_name='bitacora',
            name='en_ruta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_salida_ruta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
