# Generated by Django 5.2.14 on 2026-05-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_alter_bitacora_options_bitacora_en_ruta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='area',
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='capturo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
