# Generated by Django 5.2.14 on 2026-05-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_remove_bitacora_area_alter_bitacora_capturo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='en_ruta',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='fecha_salida_ruta',
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='situacion',
            field=models.CharField(choices=[('Asignada', 'Asignada'), ('En Ruta', 'En Ruta'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada'), ('Pendiente', 'Pendiente')], default='Asignada', max_length=20),
        ),
    ]
