# Generated by Django 5.2.12 on 2026-05-26 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0004_remove_en_ruta_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacionActualiza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion_anterior', models.CharField(choices=[('Asignada', 'Asignada'), ('En Ruta', 'En Ruta'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada'), ('No Entregada', 'No Entregada'), ('Pendiente', 'Pendiente')], max_length=20)),
                ('situacion_nueva', models.CharField(choices=[('Asignada', 'Asignada'), ('En Ruta', 'En Ruta'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada'), ('No Entregada', 'No Entregada'), ('Pendiente', 'Pendiente')], max_length=20)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('fecha_real', models.DateField(blank=True, help_text='Fecha real del evento (si aplica)', null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones (obligatorio en Cancelada/No Entregada)', null=True)),
                ('notificador_codigo', models.CharField(help_text='Código checador del notificador que realizó el cambio', max_length=15)),
                ('bitacora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_situaciones', to='bitacora.bitacora')),
            ],
            options={
                'verbose_name': 'Historial de Situación',
                'verbose_name_plural': 'Historial de Situaciones',
                'db_table': 'bitacora_situacion_actualiza',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
