# Generated by Django 5.2.14 on 2026-05-19 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100)),
                ('telefono_emergencia', models.CharField(max_length=15)),
                ('Codigo_Checador', models.CharField(max_length=15)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(help_text='The functional organizational area this agent delivers documents for.', on_delete=django.db.models.deletion.PROTECT, related_name='notificadores', to='areas.area')),
            ],
            options={
                'db_table': 'notificadores',
                'ordering': ['apellido1', 'apellido2', 'nombres'],
            },
        ),
    ]
