# Generated by Django 5.2.14 on 2026-05-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificador',
            name='Codigo_Checador',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notificador',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='notificadores/fotos/'),
        ),
    ]
